# Site Settings
title: Greg d'Eon
email: greg.l.deon@gmail.com
description: >
    Greg d'Eon's personal website
baseurl: ""
url: "https://gregdeon.github.io"
repourl: "https://github.com/gregdeon/gregdeon.github.io"
twitter_username: kynitt
github_username:  gregdeon
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', '_blog']
kramdown:
  input: GFM
